PROGRAM RUN_SOIL

IMPLICIT NONE

INTEGER, PARAMETER              :: JPIM = SELECTED_INT_KIND(9)
INTEGER, PARAMETER              :: JPRM = SELECTED_REAL_KIND(6,37)

INTEGER(KIND=JPIM), PARAMETER   :: NLAYER = 14
INTEGER(KIND=JPIM)              :: DAY
REAL(KIND=JPRM)                 :: TMEAN
REAL(KIND=JPRM)                 :: TDELTA
REAL(KIND=JPRM)                 :: PTG(NLAYER)

TMEAN  = 8.0
TDELTA = 8.0

DO DAY = 15,345,30
   CALL SOIL_T_INIT(TMEAN,TDELTA,DAY,PTG)
ENDDO

END
